services:
  active-mq:
    image: 'rmohr/activemq:latest'
    ports:
      - '8161:8161'
      - '61616:61616'
  mariadb:
    image: 'mariadb:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=booking
      - MYSQL_USER=booking
      - MYSQL_PASSWORD=booking
      - MYSQL_DATABASE=booking
    ports: 
      - '3306:3306'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
